### ISSUE TITLE
project management: TODO List

### ISSUE THREAD

**Issue by marmot8080** [marmot8080/Soom-Charm#20]
### 필수 작업 목록

- [x] shared preference를 통해 데이터를 관리하기 위한 SharedPreferenceManager 생성
- [ ] firebase를 통해 데이터를 관리하기 위한 FireBaseManager 생성
- [ ] 계정 데이터에 FireBaseManager 적용
- [x] 하트 개수 데이터에 SharedPreferenceManager 적용
- [x] 포인트의 획득 기능 추가
- [ ] 포인트의 사용 기능 추가
- [x] 포인트 데이터에 SharedPreferenceManager 적용
- [ ] 미니게임 최고 기록 데이터에 FireBaseManager 적용
- [ ] 미니게임 누적 기록 데이터에 SharedPreferenceManager 적용
- [ ] 누적 기록 시각화 기능 추가

### 선택적 작업 목록

- [ ] 즉각적인 피드백을 확인할 수 없는 미니게임(ex. 불씨 살리기 게임)에 감지 현황을 확인할 수 있는 게이지 바 추가
- [ ] 일정 시간(ex. 5분)마다 하트를 충전 가능하게 하기 위한 타이머 기능 및 충전 기능 추가
- [ ] 설정 페이지의 설정 기능 추가(ex. 소리 조절, 닉네임 변경 등)

생각나는 작업 목록을 적어봤습니다. 완료한 작업이나 기재되지 않은 추가 작업은 코멘트로 적어주시면 지속적으로 업데이트하겠습니다.

**Comment by marmot8080** [comment]
잘못 생각한 부분이 있는 것 같네요.
계정마다 데이터를 따로 저장해야 하니까 shared preference는 사용하지 않을 것 같습니다.
shared preference는 테스트에서 데이터의 입력이 필요할 때만 사용하다가 이후에 삭제하겠습니다.
